spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true #it fixes Postgres Error method org.postgresql.jdbc.PgConnection.createClob() is not implemented