server:
  port: 8081
#spring.datasource.url=jdbc:postgresql://192.168.1.4:5432
spring:
  datasource:
    driverClassName: org.postgesql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
