server:
  port: 8081
#spring.datasource.url=jdbc:postgresql://192.168.1.4:5432
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
